name: sql_serializable_postgres
description: PostgreSQL support for sql_serializable.
version: 0.1.1-dev.0
repository: https://github.com/abitofevrything/sql_serializable

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  sql_serializable: ^0.1.0-dev.0
  postgres: ^3.2.1
  collection: ^1.18.0

dev_dependencies:
  lints: ^4.0.0
