name: sql_serializable_postgres
description: PostgreSQL support for sql_serializable.
version: 0.1.1-dev.0
repository: https://github.com/abitofevrything/sql_serializable
publish_to: none

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  sql_serializable:
    git: 
      url: https://github.com/pocket-business/sql_serializable.git
      path: packages/sql_serializable
  postgres: ^3.2.1
  collection: ^1.18.0

dev_dependencies:
  lints: ^4.0.0
